In [20]:
import torch

## 反向傳播概念 requires_grad

### [首先建立一個 tensor 且 設定 requires_grad=True](#)

In [71]:
x = torch.ones(2,2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

### [這邊發現出現了 grad_fn](#)

### 發現有一條加法紀錄 記錄在 以下的記憶體位置

In [73]:
y = x + 2
print(y)

print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [74]:
z = y * y * 3
out = z.mean()

print(z)
print()
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

tensor(27., grad_fn=<MeanBackward0>)


### 建立一個隨機 tensor
##### 若沒有設 requires_grad 預設為 False

In [63]:
a = torch.randn(2, 2)

b = (a * a).sum()
print(b.requires_grad)

False


### a 做運算 並檢查 requires_grad

In [64]:
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


### 上面發現做完運算 requires grad = False
###  把 a 轉為需要 grad

In [65]:
a.requires_grad_(True)
print(a.requires_grad)

True


### 檢查做完運算後的a (這邊令為b) grad 紀錄位置

In [66]:
b = (a * a).sum()
print(b.requires_grad)
print(b.grad_fn)

True


## [做Gradients 反向傳播](#)

In [68]:
out.backward()
print(out)

tensor(27., grad_fn=<MeanBackward0>)


[Print gradients d(out)/dx](#)

In [69]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


### y.data.norm() => 這邊指說歐幾里得範數:
在 ñ 維歐幾里得空間, 向量的長度 $x = (x_{1}, x_{2},..,x_{n})$ <br><br>

則向量長度為: $||\vec{a}||_{2} := $ $\sqrt{x_{1}^2+...+x_{n}^2}$


In [97]:
x = torch.randn(3, requires_grad=True)

y = x * 2
print(y)
print(y.data.norm())
while y.data.norm() < 200:
    y = y * 2

print(y)
print(type(y))


tensor([2.3188, 0.6005, 0.0291], grad_fn=<MulBackward0>)
tensor(2.3954)
tensor([296.8028,  76.8597,   3.7294], grad_fn=<MulBackward0>)
<class 'torch.Tensor'>


In [90]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(type(y))
print(x.grad)

<class 'torch.Tensor'>
tensor([1.2800e+01, 1.2800e+02, 1.2800e-02])


In [99]:
2.3188**2 + 0.6005**2 + 0.0291**2

5.3768334399999995

In [100]:

import math

math.sqrt(2.3188**2 + 0.6005**2 + 0.0291**2)

2.39547083054668

In [101]:
2.3188**2

5.3768334399999995

In [102]:
math.sqrt(2.3188**2)

2.3188